name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Setup mise and install tools
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/mise trust mise.toml
          # Install with retry to handle "Text file busy" error
          $HOME/.local/bin/mise install || (sleep 2 && $HOME/.local/bin/mise install)
          echo "$($HOME/.local/bin/mise bin-paths)" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run Biome check
        run: bun run check
        
      - name: Check dependency versions
        run: bun run syncpack:check
        
      - name: Run knip
        run: bun x knip
        
  test-configs:
    name: Test Configuration Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: standard
            configs: 'standard'
          - name: react
            configs: 'standard,react'
          - name: test
            configs: 'standard,test'
          - name: web
            configs: 'standard,web'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Setup mise and install tools
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/mise trust mise.toml
          # Install with retry to handle "Text file busy" error
          $HOME/.local/bin/mise install || (sleep 2 && $HOME/.local/bin/mise install)
          echo "$($HOME/.local/bin/mise bin-paths)" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Validate ${{ matrix.name }} config
        run: |
          # Create a test directory
          mkdir -p /tmp/biome-test
          cd /tmp/biome-test
          
          # Build extends array from configs
          EXTENDS='['
          IFS=',' read -ra CONFIGS <<< "${{ matrix.configs }}"
          for i in "${!CONFIGS[@]}"; do
            if [ $i -gt 0 ]; then
              EXTENDS+=', '
            fi
            EXTENDS+='"'${{ github.workspace }}'/config/biome.'"${CONFIGS[$i]}"'.json"'
          done
          EXTENDS+=']'
          
          # Create biome.json that extends the config(s)
          cat > biome.json << EOF
          {
            "extends": $EXTENDS,
            "vcs": {
              "enabled": false
            }
          }
          EOF
          
          # Debug: Show the generated config
          echo "Generated biome.json:"
          cat biome.json
          
          # Copy the appropriate test file
          cp ${{ github.workspace }}/test/fixtures/test.${{ matrix.name }}.js test.js
          
          # Run check - should pass if test file matches the config format
          bun x @biomejs/biome check test.js
          
          echo "✅ Config combination for '${{ matrix.name }}' validated successfully"