name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          mise reshim
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run Biome check
        run: bun run check
        
      - name: Check dependency versions
        run: bun run syncpack:check
        
      - name: Run knip
        run: bun x knip
        
  test-configs:
    name: Test Configuration Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [standard, react, test, web]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          mise reshim
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Validate ${{ matrix.config }} config
        run: |
          mkdir -p /tmp/biome-test
          cd /tmp/biome-test
          echo '{"extends": ["${{ github.workspace }}/config/biome.${{ matrix.config }}.json"]}' > biome.json
          echo 'const test = "validation test"' > test.js
          bun x @biomejs/biome check --diagnostic-level=error test.js