name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup mise and install bun
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/mise trust mise.toml
          $HOME/.local/bin/mise install
          echo "$($HOME/.local/bin/mise bin-paths)" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run Biome check
        run: bun run check
        
      - name: Check dependency versions
        run: bun run syncpack:check
        
      - name: Run knip
        run: bun x knip
        
  test-configs:
    name: Test Configuration Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [standard, react, test, web]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup mise and install bun
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/mise trust mise.toml
          $HOME/.local/bin/mise install
          echo "$($HOME/.local/bin/mise bin-paths)" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Validate ${{ matrix.config }} config
        run: |
          mkdir -p /tmp/biome-test
          cd /tmp/biome-test
          cat > biome.json << EOF
          {
            "extends": ["${{ github.workspace }}/config/biome.${{ matrix.config }}.json"],
            "vcs": {
              "enabled": false
            }
          }
          EOF
          # Create a properly formatted test file according to the config
          cat > test.js << 'EOF'
          const test = 'validation test'
          const obj = {
            name: 'test',
            value: 42
          }
          console.log(test, obj)
          EOF
          # Run check - should pass if config is valid
          bun x @biomejs/biome check test.js
          echo "✅ Config ${{ matrix.config }} validated successfully"