name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup mise and install bun
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/mise trust mise.toml
          $HOME/.local/bin/mise install
          echo "$($HOME/.local/bin/mise bin-paths)" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run Biome check
        run: bun run check
        
      - name: Check dependency versions
        run: bun run syncpack:check
        
      - name: Run knip
        run: bun x knip
        
  test-configs:
    name: Test Configuration Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: standard
            extends: '["${{ github.workspace }}/config/biome.standard.json"]'
          - name: react
            extends: '["${{ github.workspace }}/config/biome.standard.json", "${{ github.workspace }}/config/biome.react.json"]'
          - name: test
            extends: '["${{ github.workspace }}/config/biome.standard.json", "${{ github.workspace }}/config/biome.test.json"]'
          - name: web
            extends: '["${{ github.workspace }}/config/biome.standard.json", "${{ github.workspace }}/config/biome.web.json"]'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup mise and install bun
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/mise trust mise.toml
          $HOME/.local/bin/mise install
          echo "$($HOME/.local/bin/mise bin-paths)" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Validate ${{ matrix.name }} config
        run: |
          # Create a test directory
          mkdir -p /tmp/biome-test
          cd /tmp/biome-test
          
          # Create biome.json that extends the config(s)
          cat > biome.json << EOF
          {
            "extends": ${{ matrix.extends }},
            "vcs": {
              "enabled": false
            }
          }
          EOF
          
          # Copy the appropriate test file
          cp ${{ github.workspace }}/test-fixtures/test.${{ matrix.name }}.js test.js
          
          # Run check - should pass if test file matches the config format
          bun x @biomejs/biome check test.js
          
          echo "✅ Config combination for '${{ matrix.name }}' validated successfully"