name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For creating releases
      packages: write  # For publishing to GitHub Packages
      id-token: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Setup mise and install tools
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          $HOME/.local/bin/mise trust mise.toml
          # Install with retry to handle "Text file busy" error
          $HOME/.local/bin/mise install || (sleep 2 && $HOME/.local/bin/mise install)
          echo "$($HOME/.local/bin/mise bin-paths)" >> $GITHUB_PATH
          
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hidekitux'
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Generate changelog
        run: bun run changelog
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            config/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}